import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "sonner"
import { Card, CardContent } from "./_components/ui/card"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="dark">
        {children}
        <Toaster richColors position="top-center" />

 <footer>
        {/* FOOTER */}
        <Card className="mt-6 rounded-none">
          <CardContent className="px-5">
            <p className="text-sm text-center">© 2025 Copyright <span>Murilo Boaro</span></p>
          </CardContent>
        </Card>
      </footer>
        
      </body>
    </html>
  )
}